name: number_system_converter
description: A mobile app for converting numbers between different number systems
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Add app icon
  # icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png" # see https://flutter.dev/to/font-from-package
